// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreen() {
  return window['go']['app']['App']['CaptureScreen']();
}

export function CaptureScreenAndScanQR() {
  return window['go']['app']['App']['CaptureScreenAndScanQR']();
}

export function HandlerSecret() {
  return window['go']['app']['App']['HandlerSecret']();
}
