// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTwoFA(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['AddTwoFA'](arg1, arg2, arg3, arg4, arg5);
}

export function CaptureScreenAndScanQR() {
  return window['go']['app']['App']['CaptureScreenAndScanQR']();
}

export function DeleteTwoFA(arg1) {
  return window['go']['app']['App']['DeleteTwoFA'](arg1);
}

export function GetOTPAndTimeExp(arg1) {
  return window['go']['app']['App']['GetOTPAndTimeExp'](arg1);
}

export function GetTwoFAs() {
  return window['go']['app']['App']['GetTwoFAs']();
}

export function HandlerSecret(arg1) {
  return window['go']['app']['App']['HandlerSecret'](arg1);
}

export function HandlerSecretTest(arg1) {
  return window['go']['app']['App']['HandlerSecretTest'](arg1);
}

export function UpdateTwoFA(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['UpdateTwoFA'](arg1, arg2, arg3, arg4, arg5);
}
