// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CaptureScreen():Promise<string>;

export function CaptureScreenAndScanQR():Promise<string>;

export function HandlerSecret():Promise<string>;
