// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function AddTwoFA(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<number>;

export function CaptureScreenAndScanQR():Promise<string>;

export function DeleteTwoFA(arg1:number):Promise<void>;

export function GetOTPAndTimeExp(arg1:string):Promise<app.OTPAndTimeExp>;

export function GetTwoFAs():Promise<Array<{[key: string]: any}>>;

export function HandlerSecret(arg1:string):Promise<string>;

export function HandlerSecretTest(arg1:string):Promise<string>;

export function UpdateTwoFA(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<void>;
